DROP TABLE IF EXISTS SEGMENTS
CREATE TABLE SEGMENTS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    percent REAL
)

DROP TABLE IF EXISTS USERS_SEGMENTS
CREATE TABLE USERS_SEGMENTS (
    id SERIAL PRIMARY KEY,
    segment_id INT NOT NULL ,
    ttl TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (segment_id) REFERENCES SEGMENTS(id)
)

DROP TABLE IF EXISTS USERS
CREATE TABLE USERS (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    segment_id INT,
    FOREIGN KEY (serment_id) REFERENCES USERS_SEGMENTS(id)
)

DROP TABLE IF EXISTS ACTIONS
CREATE TABLE ACTIONS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
)

DROP TABLE IF EXISTS OPERATIONS
CREATE TABLE OPERATIONS (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    segment_id INT NOT NULL,
    action_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (segment_id) REFERENCES SEGMENTS(id),
    FOREIGN KEY (operation_id) REFERENCES OPERATIONS(id)
)