version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_PASSWORD=BenQuB43
      - POSTGRES_USER=postgres
    restart: unless-stopped
    networks:
      - go_develop

  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - "8089:8081"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - go_develop

networks:
  go_develop:
    driver: bridge
volumes:
  pg-data:
