version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: unless-stopped

  dynamic-user-segmentation:
    container_name: dynamic-user-segmentation
    build: .
    env_file:
      - .env
    ports:
      - "8089:8081"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg-data:
