app:
  name: 'dynamic-user-segmentation'
  version: '1.0.0'
  env: 'local'

http:
  host: localhost
  port: 8081

log:
  level: 'debug'

storage:
  max_pool_size: 20
  host: localhost
  port: 5432
  user: postgres
  password: BenQuB43
  database: postgres

jwt:
  signKey: '7enZBcDhisUZRdx5UjxNVmSdXwPD_vGRow3s7xv1elU='
  token_ttl: 120m

hash:
  salt: 'XvCwSGU/hvj7I5UO2oplzg=='